name: Sync CouchDB → Pages

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull notes from CouchDB
        run: |
          python3 - <<'PY'
          import requests, json, os, base64
          ENDPOINT = 'http://62.234.148.102:5984/obsidiannotes'
          USER, PASS = 'admin', '${{ secrets.COUCHDB_PASSWORD }}'
          OUT_DIR = 'content'
          os.makedirs(OUT_DIR, exist_ok=True)

          rows = requests.get(f'{ENDPOINT}/_all_docs?include_docs=true', auth=(USER, PASS)).json()['rows']
          for row in rows:
              doc = row['doc']
              if doc.get('type') not in {'plain', 'newnote'}:
                  continue
              note_name = doc['_id']
              if not note_name.endswith('.md'):
                  note_name += '.md'
              content = ''
              for cid in doc.get('children', []):
                  chunk = requests.get(f'{ENDPOINT}/{cid}', auth=(USER, PASS)).json()
                  data = chunk.get('data', '')
                  if isinstance(data, dict):
                      data = base64.b64decode(data['data']).decode('utf-8', 'ignore')
                  content += data
              if content:
                  with open(os.path.join(OUT_DIR, note_name), 'w', encoding='utf-8') as f:
                      f.write(content)
          PY

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Build Quartz
        run: |
          npm ci
          npx quartz build

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: main
